### ISSUE TITLE
Storing char in int list

### ISSUE THREAD

**Issue by pdaniil** [AlexanderKononenko210b/Mentoring.L1.2018.ExceptionHandling#2]
https://github.com/AlexanderKononenko210b/Mentoring.L1.2018.ExceptionHandling/blob/80ac18a32500e12a805ba7473160cd6fd8636bbd/ExceptionHandling/IntParser/Parser.cs#L37-L38

Здесь лучше сделать bool (что-то типа var isNegative) флаг и не добавлять '-' в коллекцию, после же передать в метод с парсингом, чтобы под конец умножить на -1 или нет

**Comment by AlexanderKononenko210b** [comment]
Исправлено.
