### ISSUE TITLE
Exception throwing / returning status value

### ISSUE THREAD

**Issue by pdaniil** [AlexanderKononenko210b/Mentoring.L1.2018.ExceptionHandling#3]
https://github.com/AlexanderKononenko210b/Mentoring.L1.2018.ExceptionHandling/blob/80ac18a32500e12a805ba7473160cd6fd8636bbd/ExceptionHandling/IntParser/Parser.cs#L20-L30

Тут явно что-то лишнее, либо возвращаемое значение (false никогда не будет, а true проверять нет смысла, так исключений не было, собвсенно и проблем с парсингом). На мой взгляд лучше разделить

**Comment by AlexanderKononenko210b** [comment]
Разделено на два метода Parse и TryParse.
